// GENERATED by tools/malecns_stats.py from MaleCNS v1.0 real data — DO NOT EDIT.
// Source: Janelia FlyEM MaleCNS v1.0 (CC-BY), class == Kenyon_Cell, N=4062
// Fractions measured from the dataset (KCab / KCa'b' / KCg subfamilies).
// Dynamics per subtype are our design mapping (see docs/RESEARCH.md §Allen):
//   alpha-beta  -> long eligibility trace (LTM substrate)
//   alpha'-beta'-> short trace, faster plasticity (STM substrate)
//   gamma       -> intermediate
#pragma once
// self-contained: uses plain float (no dependency on core/types.hpp)
namespace malefly {
struct KcSubtypeSpec {
    const char* name;
    float frac;        // measured fraction in MaleCNS v1.0
    float tau_elig;    // s, eligibility trace time constant (design mapping)
    float eta_scale;   // plasticity rate scale (design mapping)
};
inline constexpr KcSubtypeSpec KC_SUBTYPES[3] = {
    {"alpha-beta",   0.4456f, 2.5f, 1.0f},
    {"alpha-prime-beta-prime", 0.1711f, 0.3f, 1.5f},
    {"gamma",        0.3833f, 0.8f, 1.0f},
};
inline constexpr int KC_N_SUBTYPES = 3;
}  // namespace malefly
